export function markdownSummary(data, testMeta) {
  const now = new Date().toISOString().replace("T", " ").slice(0, 19);
  const metrics = data.metrics;

  let md = `# ${testMeta.title || "Load Test Report"}\n\n`;
  md += `**Project:** IT Asset Lifecycle Management Module\n`;
  md += `**Date:** ${now}\n`;
  md += `**Tool:** k6\n`;
  md += `**Test Type:** ${testMeta.testType || "N/A"}\n\n`;
  md += `---\n\n`;

  // Per-endpoint sections
  if (testMeta && testMeta.endpoints) {
    for (const ep of testMeta.endpoints) {
      md += `## ${ep.method} \`${ep.path}\`\n\n`;
      md += `| Config | Value |\n`;
      md += `|--------|-------|\n`;
      md += `| Test Type | ${ep.testType} |\n`;
      md += `| Virtual Users | ${ep.vus} |\n`;
      md += `| Duration | ${ep.duration} |\n`;
      md += `\n`;

      const tag = ep.tag;
      const duration = findTaggedMetric(data, "http_req_duration", tag);
      const reqs = findTaggedMetric(data, "http_reqs", tag);
      const failed = findTaggedMetric(data, "http_req_failed", tag);

      md += `| Metric | Value |\n`;
      md += `|--------|-------|\n`;
      if (duration) {
        md += `| Avg | ${fmt(duration.values.avg)} |\n`;
        md += `| Min | ${fmt(duration.values.min)} |\n`;
        md += `| Max | ${fmt(duration.values.max)} |\n`;
        md += `| p(90) | ${fmt(duration.values["p(90)"])} |\n`;
        md += `| p(95) | ${fmt(duration.values["p(95)"])} |\n`;
      }
      if (reqs) {
        md += `| Total Requests | ${reqs.values.count} |\n`;
        md += `| Throughput | ${reqs.values.rate.toFixed(2)} req/s |\n`;
      }
      if (failed) {
        const rate = (failed.values.rate * 100).toFixed(2);
        md += `| Error Rate | ${rate}% |\n`;
      }
      md += `\n`;

      if (data.thresholds) {
        const relevantThresholds = Object.entries(data.thresholds).filter(
          ([name]) => name.includes(`name:${tag}`) || !name.includes("name:")
        );
        if (relevantThresholds.length > 0) {
          md += `| Threshold | Status |\n`;
          md += `|-----------|--------|\n`;
          for (const [name, info] of relevantThresholds) {
            for (const t of info.thresholds) {
              const status = t.ok ? "✅ PASS" : "❌ FAIL";
              md += `| \`${t.threshold}\` | ${status} |\n`;
            }
          }
          md += `\n`;
        }
      }

      // CloudWatch placeholder for Volume tests
      if (testMeta.testType && testMeta.testType.includes("Volume")) {
        md += `### CloudWatch Metrics (Manual)\n\n`;
        md += `> Fill in after test run. Filter CloudWatch time range: **${now}** (± 5 min)\n\n`;
        md += `| Metric | Value |\n`;
        md += `|--------|-------|\n`;
        md += `| Data Size (records in DB) | ___ |\n`;
        md += `| Lambda Duration (avg) | ___ms *(optional — check if p95 is high)* |\n`;
        md += `\n`;
      }

      md += `---\n\n`;
    }
  }

  // Overall summary
  md += `## Overall Summary\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  if (metrics.http_reqs) {
    md += `| Total Requests | ${metrics.http_reqs.values.count} |\n`;
    md += `| Overall Throughput | ${metrics.http_reqs.values.rate.toFixed(2)} req/s |\n`;
  }
  if (metrics.http_req_duration) {
    md += `| Overall Avg Response | ${fmt(metrics.http_req_duration.values.avg)} |\n`;
    md += `| Overall p(95) | ${fmt(metrics.http_req_duration.values["p(95)"])} |\n`;
  }
  if (metrics.http_req_failed) {
    md += `| Overall Error Rate | ${(metrics.http_req_failed.values.rate * 100).toFixed(2)}% |\n`;
  }
  if (metrics.data_received) {
    md += `| Data Received | ${fmtBytes(metrics.data_received.values.count)} |\n`;
  }
  if (metrics.data_sent) {
    md += `| Data Sent | ${fmtBytes(metrics.data_sent.values.count)} |\n`;
  }
  if (metrics.checks) {
    const passed = metrics.checks.values.passes;
    const failed = metrics.checks.values.fails;
    const total = passed + failed;
    const passRate = total > 0 ? ((passed / total) * 100).toFixed(1) : "N/A";
    md += `| Checks Passed | ${passed}/${total} (${passRate}%) |\n`;
  }
  md += `\n`;

  md += `---\n*Generated by k6 load test*\n`;
  return md;
}

function findTaggedMetric(data, metricName, tag) {
  const taggedName = `${metricName}{name:${tag}}`;
  if (data.metrics[taggedName]) return data.metrics[taggedName];
  return data.metrics[metricName] || null;
}

function fmt(ms) {
  if (ms === undefined || ms === null) return "N/A";
  return ms < 1000 ? `${ms.toFixed(2)}ms` : `${(ms / 1000).toFixed(2)}s`;
}

function fmtBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
